### ISSUE TITLE
SMTP mail issue after registration.

### ISSUE THREAD

**Issue by AlkenD** [polterguy/magic#190] opened 2022-07-25 08:26 UTC
**Describe the bug**
After registering a user the Welcome MAIL is not receiving in the registered user's inbox

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure the gmail SMTP settings
2. Create a new user directly in the Aista Magic Dashboard to the following endpoint 'magic/system/auth/register'
3. Submit the below payload

```
{
    "username": "RECEIVER@gmail.com",
    "password": "ThisIsAPassword@123",
    "frontendUrl": "https://demo.com/verify",
    "subject": "Welcome",
    "extra": {
      "name": "Test User"
    }
}
```

4. A success message is shown.

**Expected behaviour**
After a user registers a MAIL should arrive in the receiver’s inbox

**Screenshots**
--Not Applicable--

**Desktop (please complete the following information):**
 - OS: macOS Monterey Version 12.4 (21F79)
 - Browser Chrome
 - Version 103.0.5060.134 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
--Not Applicable--

**Additional context**
Note -- The SMTP service is working as i can send a test mail from the Aista Magic Dashboard' Evaluator section

Here is the code snippet that works

```
mail.smtp.send
   message
      to
         Your Name Here:RECEIVER@gmail.com
      from
         Whatever From Name Here:admin@demo.com
      subject:Test email from Magic
      entity:text/plain
         content:This is a test!
```

**Comment by polterguy** [comment] 2022-07-25 09:41
Give me some time and I'll come back to you on this one. What _version_ of Magic are you using?

**Comment by polterguy** [comment] 2022-07-25 09:58
I am able to reproduce it. We'll probably have a solution to you fast, hopefully by the end of the day :)

**Comment by polterguy** [comment] 2022-07-25 10:09
The problem is that even though you _can_ use an email as username(s), the system doesn't enforce this, to allow for having usernames being _"public handles"_, for social media sites etc, where the username is publicly displayed, but the email is _not_ publicly displayed. Hence, we need to separate the username and the email address. To provide an email to the system during registrations, you'll have to slightly modify your payload to the following.

```json
{
    "username": "RECEIVER@gmail.com",
    "password": "ThisIsAPassword@123",
    "frontendUrl": "https://demo.com/verify",
    "subject": "Welcome",
    "extra": {
      "name": "Test User",
      "email": "RECEIVER@gmail.com"
    }
}
```

**Notice** - The added `email` extra field ...

The above of course allows you to use a _different_ value as usernames if you wish - But this is optional. If you want to enforce usernames being the same as email address, you're of course free to do this as you see fit in your own (frontend/middleware) logic ...

Out of curiosity, I assume you found the recipe of how to implement user registrations _"somewhere"_ out there? Do you have a link to it? Such that we can edit its wording? The ability to separate usernames and email addresses is a fairly new addition to the core, and hence there might be documentation out there that doesn't reflect this behaviour ...

Please close the issue if this fixes it for you :)

**Comment by AlkenD** [comment] 2022-07-25 10:25
> The problem is that even though you _can_ use an email as username(s), the system doesn't enforce this, to allow for having usernames being _"public handles"_, for social media sites etc, where the username is publicly displayed, but the email is _not_ publicly displayed. Hence, we need to separate the username and the email address. To provide an email to the system during registrations, you'll have to slightly modify your payload to the following.
> 
> ```json
> {
>     "username": "RECEIVER@gmail.com",
>     "password": "ThisIsAPassword@123",
>     "frontendUrl": "https://demo.com/verify",
>     "subject": "Welcome",
>     "extra": {
>       "name": "Test User",
>       "email": "RECEIVER@gmail.com"
>     }
> }
> ```
> 
> **Notice** - The added `email` extra field ...
> 
> The above of course allows you to use a _different_ value as usernames if you wish - But this is optional. If you want to enforce usernames being the same as email address, you're of course free to do this as you see fit in your own (frontend/middleware) logic ...
> 
> Out of curiosity, I assume you found the recipe of how to implement user registrations _"somewhere"_ out there? Do you have a link to it? Such that we can edit its wording? The ability to separate usernames and email addresses is a fairly new addition to the core, and hence there might be documentation out there that doesn't reflect this behaviour ...
> 
> Please close the issue if this fixes it for you :)

https://docs.aista.com/tutorials/registering/

here is the link to the tutorial which i referred.

-- 
btw an offtopic question so i just tried registering a user using a basic react frontend but for some reason i'm facing CORS issue even though the docs stage that if no url is assigned in the magic config it defaults to allow all.

**Comment by polterguy** [comment] 2022-07-25 11:11
> just tried registering a user using a basic react frontend but for some reason i'm facing CORS

Ouch! It shouldn't have any CORS issues - But you _can_ override the CORS accepted frontends in its `frontends` declaration in the _"Config"_ menu item ...

> here is the link to the tutorial which i referred

Thank you, we'll edit it in accordance to how it actually is ... :)

**Comment by AlkenD** [comment] 2022-07-25 11:18
> 

the problem still persists should i open a new issue ?

**Comment by polterguy** [comment] 2022-07-25 11:31
> the problem still persists should i open a new issue

Yes please, it makes things easier to track on a per issue basis ...

I'll close this guy ...

**Closed by polterguy** 2022-07-25 11:31 UTC

**Comment by polterguy** [comment] 2022-07-25 12:02
I have updated [the relevant documentation](https://docs.aista.com/tutorials/registering/) now - Thank you :)
